version: '3.6'
services:
  #MariaDb Service
  db:
    image: mariadb:10.3.27
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: database
    volumes:
      - db_data:/var/lib/mysql-files/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
volumes:
  db_data:
    driver: local
